package kerberos

import (
	"reflect"

	"github.com/vincd/savoir/modules/sekurlsa/packages/globals"
	"github.com/vincd/savoir/utils/binary"
	"github.com/vincd/savoir/windows"
)

var (
	// kerberos Logon Session
	kiwiKerberosLogonSession51Type      = reflect.TypeOf(KiwiKerberosLogonSession51{})
	kiwiKerberosLogonSessionType        = reflect.TypeOf(KiwiKerberosLogonSession{})
	kiwiKerberosLogonSession10Type      = reflect.TypeOf(KiwiKerberosLogonSession10{})
	kiwiKerberosLogonSession10_1607Type = reflect.TypeOf(KiwiKerberosLogonSession10_1607{})

	// Kerberos Credntials
	kiwiGenericPrimaryCredentialType          = reflect.TypeOf(globals.KiwiGenericPrimaryCredential{})
	kiwiKerberosPrimaryCredential10Type       = reflect.TypeOf(KiwiKerberosPrimaryCredential10{})
	kiwiKerberosPrimaryCredential10_1607_Type = reflect.TypeOf(KiwiKerberosPrimaryCredential10_1607{})

	// Kerberos Internet Ticket
	KiwiKerberosInternalTicket51Type      = reflect.TypeOf(KiwiKerberosInternalTicket51{})
	KiwiKerberosInternalTicket52Type      = reflect.TypeOf(KiwiKerberosInternalTicket52{})
	KiwiKerberosInternalTicket60Type      = reflect.TypeOf(KiwiKerberosInternalTicket60{})
	KiwiKerberosInternalTicket6Type       = reflect.TypeOf(KiwiKerberosInternalTicket6{})
	KiwiKerberosInternalTicket10Type      = reflect.TypeOf(KiwiKerberosInternalTicket10{})
	KiwiKerberosInternalTicket10_1607Type = reflect.TypeOf(KiwiKerberosInternalTicket10_1607{})
)

var kerberosSignatures = []globals.Signature{
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindowsXP,
		BuildNumberMax:        windows.BuildNumberWindows2K3,
		Pattern:               []byte{0x48, 0x3b, 0xfe, 0x0f, 0x84},
		Offsets: []int64{
			int64(-4),
			int64(0),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession51Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession51Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "UserName", true),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Domain", true),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Password", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession51Type, "Tickets1", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession51Type, "Tickets2", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession51Type, "Tickets3", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "Flink", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "ServiceName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "ClientName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "TargetName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "StartTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "EndTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "RenewUntil", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "DomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "TargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "AltTargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "Description", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "TicketFlags", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "KeyType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "Key", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "TicketEncType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "TicketKvno", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "Ticket", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows2K3,
		BuildNumberMax:        windows.BuildNumberWindowsVista,
		Offsets: []int64{
			int64(-4),
			int64(1),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "UserName", true),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Domain", true),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Password", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets1", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets2", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets3", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "Flink", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "ServiceName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "ClientName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "TargetName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "StartTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "EndTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "RenewUntil", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "DomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "TargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "AltTargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "Description", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "TicketFlags", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "KeyType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "Key", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "TicketEncType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "TicketKvno", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "Ticket", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindowsVista,
		BuildNumberMax:        windows.BuildNumberWindows7,
		Pattern:               []byte{0x48, 0x8b, 0x18, 0x48, 0x8d, 0x0d},
		Offsets: []int64{
			int64(6),
			int64(2),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "UserName", true),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Domain", true),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Password", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets1", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets2", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets3", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "Flink", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "ServiceName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "ClientName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "TargetName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "StartTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "EndTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "RenewUntil", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "DomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "TargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "AltTargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "Description", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "TicketFlags", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "KeyType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "Key", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "TicketEncType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "TicketKvno", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "Ticket", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows7,
		BuildNumberMax:        windows.BuildNumberWindows8,
		Pattern:               []byte{0x48, 0x8b, 0x18, 0x48, 0x8d, 0x0d},
		Offsets: []int64{
			int64(6),
			int64(3),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "UserName", true),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Domain", true),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Password", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets1", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets2", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets3", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Flink", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "ServiceName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "ClientName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TargetName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "StartTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "EndTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "RenewUntil", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "DomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "AltTargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Description", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketFlags", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "KeyType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Key", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketEncType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketKvno", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Ticket", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows8,
		BuildNumberMax:        windows.BuildNumberWindows10_1507,
		Pattern:               []byte{0x48, 0x8b, 0x18, 0x48, 0x8d, 0x0d},
		Offsets: []int64{
			int64(6),
			int64(4),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "UserName", true),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Domain", true),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Password", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets1", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets2", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets3", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Flink", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "ServiceName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "ClientName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TargetName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "StartTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "EndTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "RenewUntil", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "DomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "AltTargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Description", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketFlags", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "KeyType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Key", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketEncType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketKvno", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Ticket", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows10_1507,
		BuildNumberMax:        windows.BuildNumberWindows10_1511,
		Pattern:               []byte{0x48, 0x8b, 0x18, 0x48, 0x8d, 0x0d},
		Offsets: []int64{
			int64(6),
			int64(5),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10Type, "Password", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10Type, "Tickets1", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10Type, "Tickets2", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10Type, "Tickets3", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Flink", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "ServiceName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "ClientName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TargetName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "StartTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "EndTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "RenewUntil", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "DomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "AltTargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Description", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketFlags", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "KeyType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Key", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketEncType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketKvno", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Ticket", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows10_1511,
		BuildNumberMax:        windows.BuildNumberWindows10_1607,
		Pattern:               []byte{0x48, 0x8b, 0x18, 0x48, 0x8d, 0x0d},
		Offsets: []int64{
			int64(6),
			int64(6),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10Type, "Password", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10Type, "Tickets1", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10Type, "Tickets2", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10Type, "Tickets3", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "Flink", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "ServiceName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "ClientName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "TargetName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "StartTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "EndTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "RenewUntil", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "DomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "TargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "AltTargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "Description", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "TicketFlags", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "KeyType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "Key", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "TicketEncType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "TicketKvno", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10Type, "Ticket", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows10_1607,
		Pattern:               []byte{0x48, 0x8b, 0x18, 0x48, 0x8d, 0x0d},
		Offsets: []int64{
			int64(6),
			int64(7),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10_1607Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10_1607Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10_1607_Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10_1607_Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10_1607_Type, "Password", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10_1607Type, "Tickets1", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10_1607Type, "Tickets2", true),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10_1607Type, "Tickets3", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "Flink", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "ServiceName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "ClientName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "TargetName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "StartTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "EndTime", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "RenewUntil", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "DomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "TargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "AltTargetDomainName", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "Description", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "TicketFlags", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "KeyType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "Key", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "TicketEncType", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "TicketKvno", true),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "Ticket", true),
		},
	},

	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindowsXP,
		BuildNumberMax:        windows.BuildNumberWindows2K3,
		Pattern:               []byte{0x8b, 0x7d, 0x08, 0x8b, 0x17, 0x39, 0x50},
		Offsets: []int64{
			int64(-8),
			int64(0),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession51Type, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession51Type, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "UserName", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Domain", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Password", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession51Type, "Tickets1", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession51Type, "Tickets2", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession51Type, "Tickets3", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "Flink", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "ServiceName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "ClientName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "TargetName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "StartTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "EndTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "RenewUntil", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "DomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "TargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "AltTargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "Description", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "TicketFlags", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "KeyType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "Key", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "TicketEncType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "TicketKvno", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket51Type, "Ticket", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindows2K3,
		BuildNumberMax:        windows.BuildNumberWindowsVista,
		Pattern:               []byte{0x8b, 0x7d, 0x08, 0x8b, 0x17, 0x39, 0x50},
		Offsets: []int64{
			int64(-8),
			int64(1),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "UserName", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Domain", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Password", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets1", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets2", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets3", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "Flink", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "ServiceName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "ClientName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "TargetName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "StartTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "EndTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "RenewUntil", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "DomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "TargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "AltTargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "Description", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "TicketFlags", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "KeyType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "Key", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "TicketEncType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "TicketKvno", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket52Type, "Ticket", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindowsVista,
		BuildNumberMax:        windows.BuildNumberWindows7,
		Pattern:               []byte{0x53, 0x8b, 0x18, 0x50, 0x56},
		Offsets: []int64{
			int64(-11),
			int64(2),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "UserName", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Domain", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Password", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets1", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets2", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets3", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "Flink", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "ServiceName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "ClientName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "TargetName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "StartTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "EndTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "RenewUntil", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "DomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "TargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "AltTargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "Description", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "TicketFlags", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "KeyType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "Key", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "TicketEncType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "TicketKvno", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket60Type, "Ticket", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindows7,
		BuildNumberMax:        windows.BuildNumberWindows8,
		Pattern:               []byte{0x53, 0x8b, 0x18, 0x50, 0x56},
		Offsets: []int64{
			int64(-11),
			int64(3),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "UserName", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Domain", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Password", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets1", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets2", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets3", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Flink", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "ServiceName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "ClientName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TargetName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "StartTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "EndTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "RenewUntil", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "DomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "AltTargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Description", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketFlags", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "KeyType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Key", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketEncType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketKvno", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Ticket", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindows8,
		BuildNumberMax:        windows.BuildNumberWindowsBlue,
		Pattern:               []byte{0x57, 0x8b, 0x38, 0x50, 0x68},
		Offsets: []int64{
			int64(-14),
			int64(4),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "UserName", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Domain", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Password", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets1", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets2", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets3", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Flink", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "ServiceName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "ClientName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TargetName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "StartTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "EndTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "RenewUntil", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "DomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "AltTargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Description", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketFlags", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "KeyType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Key", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketEncType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketKvno", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Ticket", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindowsBlue,
		BuildNumberMax:        windows.BuildNumberWindows10_1507,
		Pattern:               []byte{0x56, 0x8b, 0x30, 0x50, 0x57},
		Offsets: []int64{
			int64(-15),
			int64(4),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "UserName", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Domain", false),
			binary.GetStructureFieldOffset(kiwiGenericPrimaryCredentialType, "Password", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets1", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets2", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSessionType, "Tickets3", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Flink", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "ServiceName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "ClientName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TargetName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "StartTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "EndTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "RenewUntil", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "DomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "AltTargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Description", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketFlags", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "KeyType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Key", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketEncType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketKvno", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Ticket", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindows10_1507,
		BuildNumberMax:        windows.BuildNumberWindows10_1511,
		Pattern:               []byte{0x56, 0x8b, 0x30, 0x50, 0x57},
		Offsets: []int64{
			int64(-15),
			int64(5),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10Type, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10Type, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10Type, "UserName", false),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10Type, "Domain", false),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10Type, "Password", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10Type, "Tickets1", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10Type, "Tickets2", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10Type, "Tickets3", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Flink", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "ServiceName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "ClientName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TargetName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "StartTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "EndTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "RenewUntil", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "DomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "AltTargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Description", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketFlags", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "KeyType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Key", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketEncType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "TicketKvno", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket6Type, "Ticket", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindows10_1511,
		BuildNumberMax:        windows.BuildNumberWindows10_1903,
		Pattern:               []byte{0x56, 0x8b, 0x30, 0x50, 0x57},
		Offsets: []int64{
			int64(-15),
			int64(7),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10_1607Type, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10_1607Type, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10_1607_Type, "UserName", false),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10_1607_Type, "Domain", false),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10_1607_Type, "Password", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10_1607Type, "Tickets1", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10_1607Type, "Tickets2", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10_1607Type, "Tickets3", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "Flink", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "ServiceName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "ClientName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "TargetName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "StartTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "EndTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "RenewUntil", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "DomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "TargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "AltTargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "Description", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "TicketFlags", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "KeyType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "Key", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "TicketEncType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "TicketKvno", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "Ticket", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindows10_1903,
		Pattern:               []byte{0x56, 0x8b, 0x30, 0x50, 0x53},
		Offsets: []int64{
			int64(-15),
			int64(7),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10_1607Type, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10_1607Type, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10_1607_Type, "UserName", false),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10_1607_Type, "Domain", false),
			binary.GetStructureFieldOffset(kiwiKerberosPrimaryCredential10_1607_Type, "Password", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10_1607Type, "Tickets1", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10_1607Type, "Tickets2", false),
			binary.GetStructureFieldOffset(kiwiKerberosLogonSession10_1607Type, "Tickets3", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "Flink", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "ServiceName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "ClientName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "TargetName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "StartTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "EndTime", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "RenewUntil", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "DomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "TargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "AltTargetDomainName", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "Description", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "TicketFlags", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "KeyType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "Key", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "TicketEncType", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "TicketKvno", false),
			binary.GetStructureFieldOffset(KiwiKerberosInternalTicket10_1607Type, "Ticket", false),
		},
	},
}
