name: Build and publish Savoir

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.0'
      
      - name: Run build
        run: |
          make build
  
      - name: Publish Savoir latest version 
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/savoir-*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
